version: '3'
services:
  tensorflow-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app
      - ./models:/models
      - ./results:/results
      - /mnt/AI_new/cache_back/_100batch:/data
    devices:
      - /dev/dri
      - /dev/kfd
    working_dir: /app
    command: [ "python3", "main.py" ]
    # command: [ "sleep", "60000000" ]
